# numpy 100本ノック問題集 - 問題 -


これは numpy メーリングリストで収集された問題集です。
この問題集の目的はクイック・レファレンスとしてもらうこと、技術者の研鑽として使ってもらうことにあります。

間違いやより賢い方法を見つけたときは、気軽にご連絡ください。
<https://github.com/rougier/numpy-100>

#### 1. `np` という名前で numpy パッケージを読み込みなさい。 (★☆☆)

In [1]:
import numpy as np

#### 2. numpy のヴァージョンと設定を表示しなさい。 (★☆☆)

In [8]:
print(np.__version__)
print(np.show_config())

1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. 要素数 10 個の null ベクトルを作りなさい。null ベクトルとは全ての要素が 0 であるベクトルである。 (★☆☆)

In [9]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  配列のメモリサイズを調べるにはどうすればいいですか? (★☆☆)

In [10]:
Z = np.zeros(10)
print(Z.size)
print(Z.itemsize)

10
8


#### 5.  コマンドラインから numpy の add 関数のドキュメントを取得するにはどうすればいいですか？(★☆☆)

In [12]:
!python -c 'import numpy as np; np.info(np.add)'

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  要素数が 10 個で、5番目の要素だけが 1 で他が 0 であるベクトルを作りなさい。 (★☆☆)

In [13]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  10 から 49 までの整数を要素としてもつベクトルを作りなさい。 (★☆☆)

In [15]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  ベクトルの要素の順番を逆にして、すなわち最後から最初に向かう順番で表示しなさい。 (★☆☆)

In [18]:
Z = np.arange(10)
print(Z[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### 9.  0 から 8 までの整数を要素としてもつ 3 × 3 の行列を作りなさい。 (★☆☆)

In [20]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. \[1,2,0,0,4,0\] の配列 (リスト) の中で、0 でない要素のインデックスを取得しなさい。 (★☆☆)
    補足：index の複数形は indices

In [24]:
n = np.nonzero([1,2,0,0,4,0])
print(n[0])

[0 1 4]


#### 11. 3 × 3 の単位行列を作りなさい。単位行列とは対角成分 (左上から右下にかけて並ぶ成分) が 1 で、他の成分が全て 0 である行列である。 (★☆☆)

In [25]:
Z = np.eye(3, 3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. 乱数を要素とする 3 × 3 × 3 の配列を作りなさい。 (★☆☆)
    乱数 = random number

In [27]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.86588699 0.74653116 0.72515545]
  [0.47789781 0.00171406 0.68324182]
  [0.02191922 0.6475753  0.76322308]]

 [[0.14495731 0.61257721 0.51311705]
  [0.05649108 0.55923726 0.51733211]
  [0.24116105 0.30804916 0.08835847]]

 [[0.17520498 0.47820525 0.91371947]
  [0.09525242 0.99774953 0.29143439]
  [0.32377649 0.75111553 0.97822799]]]


#### 13. 乱数を要素とする 10 × 10 の配列を作り、最小値と最大値を取得しなさい。 (★☆☆)

In [31]:
Z = np.random.random((10, 10))
print(Z.min())
print(Z.max())

0.02168897956915372
0.9908809473450938


#### 14. 30 個の乱数でベクトルを作り、平均を計算しなさい。 (★☆☆)

In [32]:
Z = np.random.random(30)
print(Z.mean())

0.467812063346111


#### 15. 縁 (配列の最も外側) が 1 で、内側が 0 である 2 次元配列を作りなさい。 (★☆☆)

In [37]:
Z = np.ones((5,5))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. 既に作成されている配列の外側に、新たに 0 を追加した配列を作るにはどうすればいいか? (★☆☆)

In [4]:
Z = np.ones((3,3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. 以下の処理の結果はどうなるか? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. 5 × 5 の行列で対角成分のすぐ下に 1, 2, 3, 4 が並んでいるものを作りなさい。 (★☆☆)
    diagonal = 対角線(の)

In [9]:
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. 市松模様の 8 × 8 の行列を作りなさい。 (★☆☆)

In [13]:
Z = np.zeros((8,8))
Z[0::2, 0::2] = 1
Z[1::2, 1::2] = 1
print(Z)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. (6,7,8) の形の配列を考えたとき、100 番目の要素のインデックス (x, y, z) は何か? 

In [14]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. tile 関数を使って 8 × 8 の市松模様の配列を作りなさい。 (★☆☆)

In [15]:
Z = np.tile([[1,0],[0,1]], (4,4))
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. 一様乱数を要素とする 5 × 5 の行列を標準化しなさい。標準化とは分布の平均が 0、標準偏差が 1 となるように変換することである。 (★☆☆)

In [16]:
Z = np.random.random((5,5))
m = Z.mean()
s = Z.std()
Z = (Z-m)/s
print(Z)

[[ 0.94224539  0.62483192  1.53959991  1.0210937   1.5334062 ]
 [-0.71585789 -0.92744603 -0.82940883 -1.16572071 -0.59918881]
 [ 0.65709956  0.75272798 -0.81198239  0.24447764 -0.61357047]
 [ 0.77240439  1.44827502 -1.46990465 -1.09541815  0.99803857]
 [-1.29150283  0.69342303  0.46353028 -0.689563   -1.48158982]]


#### 23. RGBA の 4 つの符号なしバイトとして色を記述するためのデータ型を作りなさい。 (★☆☆)

#### 24. 5 × 3 の行列と 3 × 2 の行列の積を計算しなさい。 (★☆☆)

In [19]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
print(A@B)
print(np.einsum('ij,jk -> ik', A, B))

[[0.9926875  0.85979295]
 [0.85234303 1.18239815]
 [0.9190848  0.78033645]
 [1.07838508 0.79393519]
 [0.77177036 0.49038941]]
[[0.9926875  0.85979295]
 [0.85234303 1.18239815]
 [0.9190848  0.78033645]
 [1.07838508 0.79393519]
 [0.77177036 0.49038941]]


#### 25. 1 次元の配列が与えられたとき、3 以上 8 以下の要素の符号を反転させなさい。 (★☆☆)

In [20]:
Z = np.random.randint(0, 10, 10)
print(Z)
Z[(3<=Z) & (Z<=8)] *= -1
print(Z)

[3 2 6 8 6 0 1 8 2 3]
[-3  2 -6 -8 -6  0  1 -8  2 -3]


#### 26. 次のスクリプトの出力はどうなるか？ (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. 整数を要素とするベクトルを考えたとき、次の中で適正に処理されるものはどれか？ (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. 次の演算の結果はどうなるか？

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. float 型の配列を 0 から遠い側の整数に丸めるにはどうすればいいか？ (★☆☆)

#### 30. 2 つの配列に共通する要素を探すにはどうすればいいか？ (★☆☆)

#### 31. すべての numpy の警告を無視するにはどうすればいいか？ (推奨しない) (★☆☆)

#### 32. 次の演算結果は `True` になるでしょうか？ (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. 昨日、今日そして明日の日にちを取得するにはどうすればいいですか？ (★☆☆)

#### 34. 2016年7月の全ての日にちを取得するにはどうすればいいか？ (★★☆)

#### 35. A と B を行列として ((A+B)\*(-A/2)) の演算をコピーせず (新たにメモリを確保せず) に計算するにはどうすればいいか？ (★★☆)

#### 36. 小数点以下の値をもつ乱数から整数部分を取得する方法を 5 つ述べなさい。(★★☆)

#### 37. 行方向 (横方向) に 0 から 4 までの整数が並んでいる 5 × 5 の行列を作りなさい。 (★★☆)

#### 38. 10 個の整数を生成し、それらで配列を構成する関数を作りなさい。 (★☆☆)

#### 39. 0 から 1 までの値 (0 と 1 を含まない) をもつ要素数 10 のベクトルを作りなさい。(★★☆)

#### 40. 10 個の乱数でベクトルを作り、大きさの順にソートしなさい。 (★★☆)

#### 41. サイズの小さな配列に対して `np.sum` より速く和を計算するにはどうすればいいか？ (★★☆)

#### 42. 乱数を要素とする配列 A と B に対して、それらが等しいかどうかをチェックするにはどうすればいいか？ (★★☆)

#### 43. 配列を編集できないように (= immutable に) しなさい。 (★★☆)

#### 44. 直交座標系 (またはデカルト座標系またはカーテシアン座標系) を表す 10 × 2 の乱数の配列を考え、それらを極座標系に変換しなさい。 (★★☆)

#### 45. 要素数 10 の乱数のベクトルを作り、最大値を 0 で置き換えなさい。 (★★☆)

#### 46. $[0, 1] \times [0, 1]$ の範囲をカバーする `(x, y)` の座標の配列を作りなさい。 (★★☆)
  $[a, b]$ は $a$ 以上 $b$ 以下の範囲を表す。

####  47. X と Y の 2 つの配列が与えられたとして、コーシー行列 $C$ を構成しなさい。$C$ の $ij$ 要素は $C_{ij} = \dfrac{1}{x_i - y_j}$ である。

#### 48. numpy で扱うことのできるそれぞれの整数型と float 型で、最小値と最大値を表示しなさい。 (★★☆)

### DOES NOT WORK!
#### 49. ある配列の全ての値を表示するにはどうすればいいか？ (★★☆)

In [2]:
## This code does not work
## numpy.set_printoptions
## https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [4]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((6,6))
print(Z)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 50. あるスカラー量と配列のベクトル量に対して、そのスカラー量に最も近いベクトルの要素を見つけるにはどうすればいいか？(★★☆)

#### 51. 位置 `(x, y)` とその位置での色 `(r, g, b)` を表す配列を作りなさい。(★★☆)


#### 52. 乱数を要素とする 100 × 2 の配列を考えて 100 個の `(x, y)` 座標の点とし、それらの点の距離を計算しなさい。 (★★☆)

#### 53. 32 bits float 型の配列を 32 bits int 型に変換するにはどうすればいいですか？

#### 54. 次のようなファイルを読むにはどうすればいいですか？(★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. numpy 形式の配列に対して `enumerate` と同様の処理をするものは何か？ (★★☆)

#### 56. 要素の値が 2 次元のガウス分布 (正規分布) に従った配列を作りなさい。(★★☆)
    ガウス分布 = Gauss distribution, Gaussian distribution
    正規分布 = normal distribution

#### 57. 2 次元配列の要素の中から $p$ 個をランダムに選び、値を代入するにはどうすればいいか？ (★★☆)

#### 58. 行列に対して、それぞれの行の平均を対応する行の要素から引きなさい。 (★★☆)

#### 59. $n$ 番目 $(n=0,1,2,3,\cdots)$ のカラム (縦方向の "列") で配列をソートするにはどうすればいいですか？(★★☆)

#### 60. 与えられた 2 次元配列で null カラム (要素が全て 0 のカラム) があるかどうか調べるにはどうすればいいか？ (★★☆)

#### 61. ある値 $a$ と与えられた配列に対して、$a$ に最も近い配列の中の値を探すにはどうすればいいか？ (★★☆)

#### 62. 1 × 3, 3 × 1 の形をもった配列を考えたとき、iterator を使ってそれらの和を計算するにはどうすればいいか？(★★☆)

#### 63. name attribute をもつ配列クラスを作りなさい。(★★☆)

#### 64. ベクトルを 2 つ考え、2つ目のベクトルの要素で指定されるインデックスをもつ1つ目の要素に1を加えなさい。(★★★)

#### 65. インデックスリスト $I$ をヒストグラムの階級値 (横軸)、配列 $X$ の $I$ に対応する要素をその階級値のカウント数として、ヒストグラムの各階級値のカウントを計算しなさい。(★★★)

#### 66. $(w,\ h,\ 3)$ の配列で ubyte 型の画像があるとき、使われている色の数を計算しなさい。(★★★)

#### 67. 4 次元配列 (インデックスを 4 つもつ配列) があるとき、後ろの 2 つの軸 (インデックス) についての和を一度に計算するにはどうすればいいか？ (★★★)

#### 68. 一様乱数を要素としてもつベクトル $D$ がある。このベクトルのそれぞれの要素の平均を計算するにはどうすればいいか？(★★★)

#### 69. 行列の積を計算した後の対角成分を取得するにはどうすればいいか？(★★★)

#### 70. 与えられたベクトルに対して、それらの要素の間に 3 つずつ 0 を挿入して新たなベクトルを作るにはどうすればいいか？(★★★)

#### 71. (5, 5, 3) 次元の配列に対して、(5, 5) 次元の配列との要素ごとの積を計算し、(5, 5, 3) 次元の配列を出力するにはどうすればいいか？(★★★)

#### 72. 2 次元以上の配列に対して、2つの行を入れ替えるにはどうすればいいか？(★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. 階級値が整数であるヒストグラムの各ビンのカウントを表す配列 C が与えられたとき、`np.bincount(A) = C` を満たす配列 A を作るにはどうすればいいか？(★★★)

#### 75. 1次元配列に対して sliding window を使った平均 (移動平均) を計算するにはどうすればいいか？(★★★)

#### 76. 1 次元配列 Z を考える。この配列から、最初の行が `(Z[0], Z[1], Z[2])`、次の行が `(Z[1], Z[2], Z[3])`、その次の行が  `(Z[2], Z[3], Z[4])` とうように 1 つずつズレながら行を作っていき、最後は  `(Z[-3], Z[-2], Z[-1])` で終わる 2 次元配列を作りなさい。(★★★)

#### 77. True と Not の反転、または float 型の数値の符号を変えるにはどうすればいいか？(★★★)

#### 78. 2 次元平面上で P0 と P1 を通る直線とある点 p を考える。その直線と点 p との距離を計算するにはどうすればいいか? (★★★)

#### 79. 2次元平面上に点の集合 P0 と P1 および P がある。点 j (`P[j]`) から直線 i (`P0[i]` と `P1[i]` を通る直線) までの距離を計算しなさい。(★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. 配列 `Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]` から配列 `R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]` を作るにはどうすればいいか？(★★★)

#### 82. 行列のランクを知るにはどうすればいいか？(★★★)

#### 83. 配列の中で最も頻度の高い値 (よく現れる値) を取得するにはどうすればいいか？

#### 84. 乱数を要素とする 10 × 10 の行列から、3 × 3 の行列のブロックを全て取り出しなさい。(★★★)

#### 85. 対称行列 `Z[i, j] = Z[j, i]` を作り出すクラスを作りなさい。(★★★)

#### 86. n × n の行列が p 個、n × 1 のベクトルが p 個ある。これらの積 (n × 1 のベクトル) を一度に計算するにはどうすればいいか？(★★★)

#### 87. 16 × 16 の配列に対して、4 × 4 ブロックの和を計算するにはどうすればいいか？(★★★)

#### 88. numpy 配列を使って人生ゲーム (Game of Life) を実装するにはどうすればいいか？(★★★)

#### 89. 配列の中で n 番目に大きな値を取得するにはどうすればいいですか？(★★★)

#### 90. 与えられた複数のベクトルに対して、直積を作りなさい。
   直積について [wiki](https://ja.wikipedia.org/wiki/%E7%9B%B4%E7%A9%8D%E9%9B%86%E5%90%88)

    呼び方： 直積 (ちょくせき)、デカルト積、カーテシャン積

#### 91. 整った配列からレコードの配列を作るにはどうすればいいか？(★★★)
    レコード record は行方向のデータの固まり

#### 92. 要素数がとても多いベクトルがあるとき、3 つの方法で要素ごとの 3 乗を計算しなさい。(★★★)

#### 93. 形状がそれぞれ (8, 3) と (2, 2) の配列 A と B がある。配列 B の各行の要素から少なくとも 1 つずつの要素を含んでいる配列 A の行を見つけなさい。ただし、含んでいる順番は問わない。(★★★)

#### 94. 10 × 3 の行列がある。各行の 3 つの要素について、等しくない値をもっている行を取得しなさい。例えば `[2, 2, 3]` のような行。(★★★)

#### 95. 整数を要素とするベクトルを binary 表示の行列に変換しなさい。(★★★)

#### 96. 与えられた 2 次元配列に対して、ユニークな配列である行を取得しなさい。(★★★)
    ユニーク unique = 唯一の, 固有の, 一意的な

#### 97. 2 つのベクトル A と B に対して、`numpy.inner`, `numpy.outer`, `numpy.sum`, そして `numpy.multiply (= A*B)` と同じ処理を `numpy.einsum` で書きなさい。(★★★)

#### 98. 2 つの座標 $x = a \phi \cos(\phi)$, $y = a \phi \sin(\phi)$ ($a$ は定数) で記述される曲線のパス (軌跡) がある。そのパスを等間隔でサンプリングするにはどうすればいいか？(★★★)

　このようなパラメータ (今の場合は $\phi$) を使った座標の表し方をパラメータ表示、媒介変数表示という。

#### 99. 整数 n と2次元配列 X が与えられたとき、要素が整数のみで和が n である行を取得しなさい。(★★★)

#### 100. 正規乱数を要素とする1次元配列に対して、ランダムサンプリングして平均をとる操作を N 回行い、平均の 2.5 パーセンタイルと 97.5 パーセンタイルを計算しなさい。(★★★)