In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数第3位まで表示
%precision 3

/Users/koretsunobuyasu/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


'%.3f'

In [3]:
#　配列の作成
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [4]:
data.dtype

dtype('int64')

In [5]:
print('次元数:', data.ndim)
print('要素数:', data.size)

次元数: 1
要素数: 10


In [6]:
#それぞれの数字を係数倍 (ここでは2倍)
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [7]:
#それぞれの要素同士での演算
print("掛け算:", np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) * np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))
print("累乗:", np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) ** 2)
print("割り算:", np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) / np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

掛け算: [10 18 24 28 30 30 28 24 18 10]
累乗: [  1   4   9  16  25  36  49  64  81 100]
割り算: [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [8]:
# 現在の値を表示
print("そのまま:", data)

# ソートした結果を表示
data.sort()
print("ソート後:", data)

そのまま: [ 9  2  3  4 10  6  7  8  1  5]
ソート後: [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# sort()するともとのデータを置き換えてしまうので、再度dataを表示するとソート後のデータになっていることが確認できる
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# 降順にソートする
data[::-1].sort()
print("ソート後:", data)

ソート後: [10  9  8  7  6  5  4  3  2  1]


In [11]:
# 最小値
print("Min:", data.min())

# 最大値
print("Max:", data.max())

# 合計
print("Sum:", data.sum())

# 積み上げ
print("Cum:", data.cumsum())

# 積み上げ割合
print("Ratio:", data.cumsum() / data.sum())

Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]
Ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [12]:
random.seed(0)

# 正規分布 (平均0, 分散1)の乱数を10個発生
rnd_data = random.randn(10)

print("乱数10個の配列:", rnd_data)

乱数10個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [13]:
# 抽出対象データ
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

# ランダム抽出
# 10個を抽出(重複あり、復元抽出)
print(random.choice(data, 10))

#　10個を抽出(重複なし、非復元抽出)
print(random.choice(data, 10, replace=False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


# 行列計算

In [15]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
array1 = np.arange(9).reshape(3, 3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
# 1行目
array1[0, :]

array([0, 1, 2])

In [19]:
# 1列目
array1[:, 0]

array([0, 3, 6])

In [20]:
array2 = np.arange(9, 18).reshape(3, 3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [21]:
# 行列の積
np.dot(array1, array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [22]:
# 要素同士の積
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [23]:
# 要素が全て0の行列
print(np.zeros((2, 3), dtype= np.int64))

#要素が全て1の行列(float)
print(np.ones((2, 3), dtype=np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


### Practiceは今回は飛ばす

# Chapter2-3

In [25]:
# 線形代数用のライブラリ
import scipy.linalg as linalg

# 最適化計算(最小値)用の関数
from scipy.optimize import minimize_scalar

In [26]:
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

# 行列式
print("行列式")
print(linalg.det(matrix))

行列式
-4.0


In [27]:
# 逆行列
print('逆行列')
print(linalg.inv(matrix))

逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [28]:
# 元の行列と逆行列の積は単位行列
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# 固有値と固有値ベクトルの計算
eig_value, eig_vector = linalg.eig(matrix)

print("固有値")
print(eig_value)
print("固有ベクトル")
print(eig_vector)

固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


# ニュートン法

f(x) = x² + 2x + 1

In [30]:
# 関数の定義
def my_function(x):
    return (x**2 + 2*x + 1)

In [31]:
# ニュートン法の読み込み
from scipy.optimize import newton

#計算実行
print(newton(my_function, 0))

-0.9999999852953906


In [32]:
# 計算実行
print(minimize_scalar(my_function, method = "Brent"))

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002


# Chapter2-4

In [35]:
# Series
sample_pandas_data = pd.Series([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
print(sample_pandas_data)

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64


In [37]:
# indexをアルファベットでつける
sample_pandas_index_data = pd.Series(
    [0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
    index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])
print(sample_pandas_index_data)

a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
i    80
j    90
dtype: int64


In [38]:
print("データの値: ", sample_pandas_index_data.values)
print("インデックスの値:", sample_pandas_index_data.index)

データの値:  [ 0 10 20 30 40 50 60 70 80 90]
インデックスの値: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')


In [39]:
attri_data1 = {"ID": ["100", "101", "102", "103", "104"],
                          "City": ["Tokyo", "Osaka", "Kyoto", "Hokkaido", "Tokyo"],
                          "Birth_year": [1990, 1989,  1992, 1997, 1982],
                          "Name": ["Hiroshi", "Akiko", "Yuki", "Satoru", "Steve"]}

attri_data_frame1 = DataFrame(attri_data1)

print(attri_data_frame1)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve


In [40]:
attri_data_frame_index1 = DataFrame(attri_data1, index=["a", "b", "c", "d", "e"])
print(attri_data_frame_index1)

    ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve


In [41]:
attri_data_frame_index1

ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve

In [42]:
# 転置
attri_data_frame_index1.T

a      b      c         d      e
ID              100    101    102       103    104
City          Tokyo  Osaka  Kyoto  Hokkaido  Tokyo
Birth_year     1990   1989   1992      1997   1982
Name        Hiroshi  Akiko   Yuki    Satoru  Steve

In [43]:
# 列名の指定(1つの場合)
attri_data_frame_index1.Birth_year

a    1990
b    1989
c    1992
d    1997
e    1982
Name: Birth_year, dtype: int64

In [44]:
# 列名の指定(複数の場合)
attri_data_frame_index1[["ID", "Birth_year"]]

ID  Birth_year
a  100        1990
b  101        1989
c  102        1992
d  103        1997
e  104        1982

### データの抽出

In [46]:
# 条件(フィルター)
attri_data_frame1[attri_data_frame1["City"] == "Tokyo"]

ID   City  Birth_year     Name
0  100  Tokyo        1990  Hiroshi
4  104  Tokyo        1982    Steve

In [47]:
attri_data_frame1["City"] == 'Tokyo'

0     True
1    False
2    False
3    False
4     True
Name: City, dtype: bool

In [48]:
# 条件(フィルター、複数の値)
attri_data_frame1[attri_data_frame1["City"].isin(['Tokyo', 'Osaka'])]

ID   City  Birth_year     Name
0  100  Tokyo        1990  Hiroshi
1  101  Osaka        1989    Akiko
4  104  Tokyo        1982    Steve

In [50]:
# 誕生年が1990以前
attri_data_frame1[attri_data_frame1["Birth_year"] < 1990]

ID   City  Birth_year   Name
1  101  Osaka        1989  Akiko
4  104  Tokyo        1982  Steve

In [52]:
attri_data_frame1.drop(['Birth_year'], axis=1)

ID      City     Name
0  100     Tokyo  Hiroshi
1  101     Osaka    Akiko
2  102     Kyoto     Yuki
3  103  Hokkaido   Satoru
4  104     Tokyo    Steve